---
- name: Install Webserver Dependencies
  apt:
    name:
      - apache2
      - openssl
      - libapache2-mod-auth-mellon
      - ntpdate
      - php
      - php-fpm
    state: present

- name: Enable Apache
  service:
    name: apache2
    state: started
    enabled: true
